spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: notification-api
        instance-id: notification-api
kafka:
  bootstrap: localhost:9092
  group:
    id: creditConsumers
  topic:
    check: CREDIT_CHECK
    payed: CREDIT_PAYED
    payment: CREDIT_PAYMENT
server:
  port: 7001

