spring:
  application:
    name: notification-api
  config:
    import:
      - "optional:configserver:http://localhost:8888/"
  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    config:
      enabled: false
    consul:
      host: consul-server1
      port: 8500
      discovery:
        service-name: notification-api
        instance-id: notification-api
kafka:
  bootstrap: broker:9092
  group:
    id: creditConsumers
  topic:
    check: CREDIT_CHECK
    payed: CREDIT_PAYED
    payment: CREDIT_PAYMENT
server:
  port: 7002
