spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db?useSSL=false
    username: user
    password: user
  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: client-api
        instance-id: client-api
kafka:
  bootstrap: localhost:9092
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
server:
  port: 7000
